### ISSUE TITLE
초기세팅(Theme)

### ISSUE THREAD

**Issue by jwbaeck** [teamblend3/blend-dta-client#1]
- [ ] Tailwind css 설정
- [ ] 다크(라이트) 모드를 설정할 수 있는 버튼이 보여져야 한다.
- [ ]  초기 화면은 라이트 모드로 설정되어 있으며, 다크 모드 버튼 클릭 시 해당 모드로 변경되어야 한다.
- [ ]  다크 모드로 설정되어 있을 경우, 버튼 클릭 시 라이트 모드로 변경되어야 한다.
- [ ]  사용자의 현재 화면 모드를 전역 상태로 관리한다. (Zustand 를 통한 사용자 상태 관리)
- [ ]  Test 파일을 만들어야 한다.

## CSS layout
<img width="693" alt="스크린샷 2024-01-30 오후 1 43 33" src="https://github.com/teamblend3/blend-dta-client/assets/99715151/e47e089f-10b8-4550-9c55-49e634cbfb2b">

<br/>

```js
// tailwind.config.js
colors: {
 'text': 'var(--text)',
 'background': 'var(--background)',
 'primary': 'var(--primary)',
 'secondary': 'var(--secondary)',
 'accent': 'var(--accent)',
},
```

```css
/* main.css */
@layer base {
  :root {
    --text: #071206;
    --background: #f7fcf7;
    --primary: #5ec74f;
    --secondary: #94ddc1;
    --accent: #66cebe;
  }
  .dark {
    --text: #edf9ec;
    --background: #030703;
    --primary: #45ae37;
    --secondary: #226d50;
    --accent: #329a8a;
  }
},
```
